name: Linux build & tests

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Release # Change build type here.

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.2 # Update Qt version here.
        aqtversion: '>=0.9.7'

    - name: Install Boost
      shell: pwsh
      # Change Boost version here (see https://github.com/actions/boost-versions/releases).
      # See https://github.com/actions/virtual-environments/issues/2667#issue-804635858.
      run: |
        $url = "https://github.com/actions/boost-versions/releases/download/1.72.0-20200608.4/boost-1.72.0-linux-16.04-gcc-x64.tar.gz"
        (New-Object System.Net.WebClient).DownloadFile($url, "/tmp/boost.tar.gz")
        mkdir "/tmp/boost"
        tar -xzf "/tmp/boost.tar.gz" -C "/tmp/boost"
        Push-Location -Path "/tmp/boost"
        Invoke-Expression "bash ./setup.sh"

    - name: Build
      shell: bash
      run: |
        cd build
        cmake .. -DBOOST_ROOT="/opt/hostedtoolcache/boost/1.72.0/x64"
        cmake --build . --config $BUILD_TYPE

    - name: Tests
      shell: bash
      run: |
        cd build/tests/out/bin
        ./DegateTests
