name: Mac build & tests

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Release # Change build type here.

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.2 # Update Qt version here.
        aqtversion: '>=0.9.7'

    - name: Build
      shell: bash
      run: |
        brew install boost
        cd build
        cmake ..
        cmake --build . --config $BUILD_TYPE

    - name: Tests
      shell: bash
      run: |
        cd build/tests/out/bin
        ./DegateTests
