name: Linux deploy

on: [workflow_dispatch]

env:
  BUILD_TYPE: Release # Change build type here.
  BOOST_ROOT: /opt/hostedtoolcache/boost/1.72.0/x64 # Update Boost version here (See https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md to know latest supported Boost version).

jobs:
  build:
  
    runs-on: ubuntu-16.04 # Update Ubuntu version here (might be the oldest LTS for AppImage creation).

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.2 # Update Qt version here.
        aqtversion: '>=0.9.7'

    - name: Build
      shell: bash
      run: |
        cd build
        cmake ..
        cmake --build . --config $BUILD_TYPE

    - name: Prepare Degate AppImage
      shell: bash
      run: |
        cd etc
        mkdir linux_deploy
        sudo chown -R $USER:$USER linux_deploy
        cd linux_deploy
        mv ../../build/out/bin/Degate ./
        cp ../degate.desktop ./degate.desktop
        cp ../degate.png ./degate.png
        sudo apt-get install libxcb-*

    - name: Create Degate AppImage
      shell: bash
      run: |
        cd etc/
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage ./linux_deploy/Degate -appimage -extra-plugins=iconengines,platformthemes/libqgtk3.so
        cd linux_deploy/
        rm AppRun
        cp -R . ../installer/packages/Degate/data
        rm ../installer/packages/Degate/data/.keepme

    - name: Upload Degate appimage
      uses: actions/upload-artifact@v2
      with:
        name: Degate_appimage_Linux_x64
        path: etc/Degate*.AppImage
        
    - name: Upload Degate binaries
      uses: actions/upload-artifact@v2
      with:
        name: Degate_binaries_Linux_x64
        path: etc/linux_deploy/
        
    - name: Create Degate installer
      shell: bash
      # Update the Qt Installer Framework (ifw) version here (by providing the exe download link and changing the exe name/path).
      run: |
        sudo apt install p7zip-full
        cd etc/installer
        wget https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/qt.tools.ifw.40/4.0.1-202012091043ifw-linux-x64.7z
        7z x 4.0.1-202012091043ifw-linux-x64.7z -y
        ./Tools/QtInstallerFramework/4.0/bin/binarycreator --offline-only -c config/config.xml -p packages "Degate_offline_installer_Linux_x64"
        ./Tools/QtInstallerFramework/4.0/bin/binarycreator --online-only -c config/config.xml -p packages "Degate_online_installer_Linux_x64"
        
    - name: Upload Degate offline installer
      uses: actions/upload-artifact@v2
      with:
        name: Degate_offline_installer_Linux_x64
        path: etc/installer/Degate_offline_installer_Linux_x64

    - name: Upload Degate online installer
      uses: actions/upload-artifact@v2
      with:
        name: Degate_online_installer_Linux_x64
        path: etc/installer/Degate_online_installer_Linux_x64
        
    - name: Create Degate update
      shell: bash
      run: |
        cd etc/installer
        ./Tools/QtInstallerFramework/4.0/bin/repogen -p packages repository
      
    - name: Upload Degate update
      uses: actions/upload-artifact@v2
      with:
        name: Degate_update_Linux_x64
        path: etc/installer/repository
